### ISSUE TITLE
is there a way to avoid typescript errors in the Jest test here? 

### ISSUE THREAD

**Issue by bml1g12** [codetheworld-io/ts-jest-serverless#1]
https://github.com/codetheworld-io/ts-jest-serverless/blob/main/src/functions/hello/handler.spec.ts
```
    let main;
        const event = {
            body: {
                name: 'test-name',
            },
        } as any;
 const actual = await main(event, {});
```
TS7005: Variable 'main' implicitly has an 'any' type.

**Comment by hoangsetup** [comment]
@bml1g12 For testing you can remove the` as any` part.

**Comment by bml1g12** [comment]
Ah yes sorry my question was a bit naive. Thanks for the great repo, it's got me sorted on how to mock out middy. I notice that the latest jest version uses slightly different syntax. In case it's helpful  for others:

```
import {jest} from '@jest/globals'
import {Handler} from 'aws-lambda';
jest.mock('#libs/middleware');
describe('ping', () => {
    const mockedMiddyfy = jest.mocked(middyfy, true);
    beforeEach(async () => {

        mockedMiddyfy.mockImplementation((handler: Handler) => {
            return handler as never;
        });

    });
```

My problem seems to be more of a TypeScript issue, in that I have some Middy middleware normalising the types, and struggling to get generate sensible types event that matches what it expects - but not relevant to the topic of this repo so I'll deal with it elsewhere :+1:
